/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package analyzer;

/**
 *
 * @author Klint
 */
public class AnalyzerFrame extends javax.swing.JFrame {

    /**
     * Creates new form AnalyzerFrame
     */
    public AnalyzerFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        coverPanel = new javax.swing.JPanel();
        startButton = new javax.swing.JButton();
        coverLabel = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        backButton = new javax.swing.JButton();
        sentenceField = new javax.swing.JTextField();
        acceptLabel = new javax.swing.JLabel();
        rejectLabel = new javax.swing.JLabel();
        sentenceRemarks = new javax.swing.JLabel();
        sentenceAnalyzer = new javax.swing.JButton();
        mainLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(720, 450));
        getContentPane().setLayout(new java.awt.CardLayout());

        coverPanel.setMinimumSize(new java.awt.Dimension(800, 500));
        coverPanel.setPreferredSize(new java.awt.Dimension(800, 500));
        coverPanel.setLayout(null);

        startButton.setBackground(new java.awt.Color(0, 0, 0, 0));
        startButton.setForeground(new java.awt.Color(0, 0, 0, 0));
        startButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/analyzer/startButton.png"))); // NOI18N
        backButton.setBorderPainted(false);
        backButton.setContentAreaFilled(false);
        backButton.setOpaque(false);
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });
        coverPanel.add(startButton);
        startButton.setBounds(330, 300, 170, 110);

        coverLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/analyzer/cover.jpg"))); // NOI18N
        coverLabel.setText("jLabel1");
        coverPanel.add(coverLabel);
        coverLabel.setBounds(0, 0, 800, 500);

        getContentPane().add(coverPanel, "card2");

        mainPanel.setMinimumSize(new java.awt.Dimension(800, 500));
        mainPanel.setLayout(null);

        backButton.setBackground(new java.awt.Color(0, 0, 0, 0));
        backButton.setForeground(new java.awt.Color(0, 0, 0, 0));
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/analyzer/backButton.png"))); // NOI18N
        backButton.setBorderPainted(false);
        backButton.setContentAreaFilled(false);
        backButton.setOpaque(false);
        backButton.setText("RETURN");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        mainPanel.add(backButton);
        backButton.setBounds(120, 40, 100, 80);

        sentenceField.setBackground(new java.awt.Color(255, 255, 204));
        mainPanel.add(sentenceField);
        sentenceField.setBounds(60, 130, 580, 40);

        acceptLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/analyzer/accept1.png"))); // NOI18N
        mainPanel.add(acceptLabel);
        acceptLabel.setBounds(360, 180, 100, 100);

        rejectLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/analyzer/reject2.png"))); // NOI18N
        mainPanel.add(rejectLabel);
        rejectLabel.setBounds(360, 180, 130, 100);

        sentenceRemarks.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sentenceRemarks.setText("jLabel1");
        mainPanel.add(sentenceRemarks);
        sentenceRemarks.setBounds(170, 290, 490, 120);

        sentenceAnalyzer.setBackground(new java.awt.Color(255, 255, 255));
        sentenceAnalyzer.setText("ANALYZE");
        sentenceAnalyzer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sentenceAnalyzerActionPerformed(evt);
            }
        });
        mainPanel.add(sentenceAnalyzer);
        sentenceAnalyzer.setBounds(650, 130, 90, 40);

        mainLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/analyzer/main.jpg"))); // NOI18N
        mainPanel.add(mainLabel);
        mainLabel.setBounds(0, 0, 800, 500);

        getContentPane().add(mainPanel, "card3");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        coverPanel.setVisible(false);
        mainPanel.setVisible(true);
        acceptLabel.setVisible(false);
        rejectLabel.setVisible(false);
    }//GEN-LAST:event_startButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        mainPanel.setVisible(false);
        coverPanel.setVisible(true);
        
    }//GEN-LAST:event_backButtonActionPerformed

    private void sentenceAnalyzerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sentenceAnalyzerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sentenceAnalyzerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnalyzerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnalyzerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnalyzerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnalyzerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnalyzerFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel acceptLabel;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel coverLabel;
    private javax.swing.JPanel coverPanel;
    private javax.swing.JLabel mainLabel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel rejectLabel;
    private javax.swing.JButton sentenceAnalyzer;
    private javax.swing.JTextField sentenceField;
    private javax.swing.JLabel sentenceRemarks;
    private javax.swing.JButton startButton;
    // End of variables declaration//GEN-END:variables
}
